# Generated by Django 4.2.1 on 2023-08-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-created_at',), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='course',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Please add alturnative text', max_length=255, null=True, verbose_name='Alturnative text'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='images/default.png', help_text='Upload a Course image', upload_to='course/', verbose_name='image'),
        ),
    ]
